### ISSUE TITLE
ios-Teste

### ISSUE THREAD

**Issue by SidneyDuarte** [vivadecora/ios-teste#2]
[Segue link](https://github.com/SidneyDuarte/VivaDecora)

Não há uso de pods ou frameworks de terceiros.

**Comment by IuryAlves** [comment]
Obrigado @SidneyDuarte , estamos avaliando.

**Comment by taciogt** [comment]
Oi @SidneyDuarte,

Gostaríamos de lhe enviar o feedback a respeito do teste. Para qual email podemos enviá-lo?

**Comment by SidneyDuarte** [comment]
sidney_silva13@outlook.com.
Agradeço a consideração pelo feedback.

**Comment by taciogt** [comment]
@SidneyDuarte 

Avaliamos seu teste e enviamos nosso feedback pelo email.
