### ISSUE TITLE
Teste Viva Decora

### ISSUE THREAD

**Issue by VicSoft** [vivadecora/ios-teste#3]
Link: [vivadecora-teste](https://github.com/VicSoft/vivadecora-teste)

Nota: Não compreendi a utilização da chave note (descrição), diante do layout proposto. Então salvei o conteúdo no banco local, porém utilizei outros campos para exibição do conteúdo para seguir o layout proposto. O mesmo acontece na tela de detalhes.

**Comment by IuryAlves** [comment]
Valeu @VicSoft, estamos avaliando.

**Comment by taciogt** [comment]
@VicSoft,

Avaliamos seu teste e enviamos nosso feedback pelo email associado a sua conta do Github.
