### ISSUE TITLE
Teste VivaDecora

### ISSUE THREAD

**Issue by weltonfs** [vivadecora/ios-teste#4]
Repositório: [https://github.com/weltonfs/TesteVD](url)
Código em Swift

**Comment by IuryAlves** [comment]
obrigado @weltonfs  estaremos avaliando.

**Comment by weltonfs** [comment]
Obrigado.

Em qui, 29 de set de 2016 às 16:16, iury notifications@github.com
escreveu:

**Comment by taciogt** [comment]
Oi @weltonfs,

Gostaríamos de lhe enviar o feedback a respeito do teste. Para qual email podemos enviá-lo?

**Comment by weltonfs** [comment]
Olá Tácio,

Pode ser nesse email mesmo.

Obrigado.

Em seg, 7 de nov de 2016 às 10:53, Tácio Tavares notifications@github.com
escreveu:

**Comment by taciogt** [comment]
Oi @weltonfs,

Caso eu responda o email, a resposta ficará disponível na issue do github. Seu email não está público e não enviamos os feedbacks publicamente para preservar a privacidade de todos os candidatos. Você pode me mandar um email diretamente para tacio.tavares@vivadecora.com.br que eu lhe encaminho o feedback.

**Comment by taciogt** [comment]
Oi @weltonfs,

Enviei por email o feedback sobre sua resposta para o teste do Viva Decora. Qualquer dúvida, o contato pode ser feito por aquele email mesmo.

Abs
